#!/usr/bin/env bash
# hlwm-utils main manu

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$SCRIPT_DIR/config"

declare options=("centered-master
dwindle
master-stack
vertical
|
reset")

choice=$(echo -e "${options[@]}" | ${DMENU} -i -p ' Select layput: ')

case "$choice" in
centered-master)
	choice="$HOME/.hlwm-utils/layouts/centered-master"
	;;
dwindle)
	choice="$HOME/.hlwm-utils/layouts/dwindle"
	;;
master-stack)
	choice="$HOME/.hlwm-utils/layouts/master-stack"
	;;
vertical)
	choice="$HOME/.hlwm-utils/layouts/vertical"
	;;
reset)
	choice="$HOME/.hlwm-utils/layouts/reset"
	;;
esac
sh $choice
