#!/bin/env bash
# hlwm-utils main manu

declare options=("layouts
frames-control
wall-menu
|
EXIT")

choice=$(echo -e "${options[@]}" | dmenu -i -p ' hlwm-utils: ')

case "$choice" in
layouts)
	choice="$HOME/.hlwm-utils/hlwm-menu/layouts-menu"
	;;
frames-control)
	choice="$HOME/.hlwm-utils/hlwm-menu/frames-control"
	;;
wall-menu)
	choice="$HOME/.hlwm-utils/hlwm-menu/wall-menu"
	;;
EXIT)
	exit 1
	;;
esac
sh $choice
