#!/bin/env bash
# wallpapers menu

declare options=("Fill
Scale
Tile")

choice=$(echo -e "${options[@]}" | dmenu -i -p ' Style: ')

case "$choice" in
Fill)
    choice="$HOME/.hlwm-utils/hlwm-menu/wall-menu/fill"
    ;;
Scale)
    choice="$HOME/.hlwm-utils/hlwm-menu/wall-menu/scale"
    ;;
Tile)
    choice="$HOME/.hlwm-utils/hlwm-menu/wall-menu/tile"
    ;;
esac
sh $choice
